CC=g++
CFLAGS=-c -Wall
LDFLAGS=
SOURCES=
OBJECTS=
EXECUTABLE=


all: checkspvect.cc
	g++ -Wall checkspvect.cc SparseVector.cc -o checkspvect

# all: tester.cc
# 	g++ -Wall tester.cc SparseVector.cc -o tester